## These two functions are meant to be used in conjunction. First creating
## a list that acts as a cache storing the inverse of the matrix, then 
## retrieving computed inverse from cache without having to recompute.

## FUNCTION: makeCacheMatrix
## USAGE: mCache <- makeCacheMatrix(m)
## Takes a matrix object as arg and returns a list used to access
## computed inverse values.

makeCacheMatrix <- function(x = matrix()) {
	i <- NULL
	
	# 	$set
	set <- function(y) {
		x <<- y
		i <<- NULL
	}
	
	# 	$get
	get <- function() x
	
	# 	$setInverse
	setInverse <- function(solve) i <<- solve
	
	# 	$getInverse 
	getInverse <- function() i
	
	list(set = set, get = get, setInverse = setInverse, 
	getInverse = getInverse)
}



## FUNCTION: cacheSolve
## USAGE: cacheSolve(mCache)
## Takes the list generated by makeCacheMatrix as arg and returns value found
## at the getInverse index. 

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        i <- x$getInverse()
        
        # If there is something there, return.
        if(!is.null(i)) {
        	message("getting cached data")
        	return(i)	
        }
        
        # Otherwise, compute inverse and return.
        data <- x$get()
        i <- solve(data, ...)
        x$setInverse(i)
        i
}
